tenforwardconsulting/subspace

ansible/roles/letsencrypt/tasks/main.yml, lib/subspace/version.rb
Small change but fixes a bug where certbot would hang waiting for user
input if you already had a cert for a domain but tried getting a new
cert with both the old and a new domain.
This happens when, for example, production is setup with a temporary url
and then the real url is added later. A new cert needs to be fetched but
without --non-interactive certbot hangs waiting for confirmation that you
want to replace the old cert (with only one domain) with the new cert
with both the old domain and the new domain.
=> Add non-interactive to certbot command. Bump version to 0.1.3

ansible/roles/letsencrypt/tasks/main.yml
Instead of midnight and noon
https://github.com/tenforwardconsulting/subspace/issues/6
=> Set letsencrypt renew task to run at 4am

ansible/roles/postgresql/templates/backup.sh
This is relevant for when we first switch from non-S3 to S3.
This change will slowly phase out the backups on the database server
as new ones are added to S3.
=> Always remove old backups

lib/subspace/commands/init.rb
Just tried using subspace init and noticed this.
=> Fix incorrect path causing  to fail

ansible/roles/common/tasks/main.yml, ansible/roles/delayed_job/tasks/main.yml, ansible/roles/nginx/tasks/main.yml, ansible/roles/papertrail/tasks/main.yml, ansible/roles/ruby-common/tasks/main.yml
We don't usually need them since our playbooks are run with `sudo: yes`,
but it's probably more correct to apply sudo only where it's needed.
Alex found these when he was doing VB stuff: https://github.com/tenforwardconsulting/ansible/commit/01252e96696a836561400f87d32bc795fd776a81. I just added them to subspace.
=> Add missing sudos

ansible/roles/letsencrypt/tasks/main.yml
Cron job no longer is --quiet and gets rid of quotes around command
that I think are causing it to fail
=> Redirect all server urls to https. Fix certbot cron job

ansible/roles/zenoamaro.postgresql/templates/postgresql.conf
See the "Migration to Version 9.5" notes here:
https://www.postgresql.org/docs/9.6/static/release-9-5.html
Notably are the removal of the checkpoint_segments option and the
ssl_renegotiation_limit configuration options.
=> Fix postgresql role for postgresql version 9.5 and greater

lib/subspace/commands/ssh.rb
let `subspace ssh <env>` use `ansible_ssh_port` from `host_vars`
=> support configuring ssh port in host_vars for `ssh` command

CHANGELOG.md, ansible/roles/rails/tasks/main.yml
It's not actually required (although rails will give you a warning
during asset precomp). There is now a separate yarn role for when it is
actually needed.
=> Don't install yarn as part of rails role

CHANGELOG.md, ansible/roles/common/tasks/main.yml, ansible/roles/common/templates/motd, ansible/roles/common/templates/terminalcolor
To test:
1. Clone local copy of subspace
2. Pick a local repo that uses subspace
3. Edit your Gemfile in that repo. Update the gem source to point to your local subspace
` gem 'subspace', path: '/Users/fred/subspace'`
4. Update your /config/provision/group_vars for an environment and add variable `terminal_env`
5. Test different values of this variable:
- Variable not defined
- Empty string
- dev
- development
- qa
- production
- some other string
(dev | development) should have a blue terminal prompt
qa should have a yellow terminal prompt
production should have a red terminal prompt with a big warning page
any other value should display a message telling you to set the terminal_env value.
=> Support terminal color prompt highlighting - blue for dev, yellow for qa, red for production.

ansible/roles/collectd/templates/delayed_job_postgres.conf
With this change, you can build graphs that break out delayed_job counts by queue, rather than seeing them all globbed together in one giant number.
When applied, you can create grafana dashboards such as...
=> Groups delayed_job count queries by queue

CHANGELOG.md, ansible/roles/common/templates/motd, ansible/roles/letsencrypt_dns/defaults/main.yml, ansible/roles/letsencrypt_dns/tasks/main.yml, ansible/roles/nginx/handlers/main.yml, lib/subspace/version.rb
Currently, the letsencrypt role uses HTTP validation, this has 2 problems:
1. It can't handle wildcards
2. It can't validate servers that are private
This PR adds a new role `letsencrypt_dns` to validate via DNS to solve the above problems. It also uses the official ansible module `acme_certificate`
Notes/Todos:
- This assumes you're using Route53
- It doesn't include anything to automatically renew the certificate via cron like the other role does
=> Add letsencrypt_dns role

CHANGELOG.md, ansible/roles/common/tasks/main.yml, ansible/roles/rails/tasks/main.yml, ansible/roles/ruby-common/tasks/main.yml, lib/subspace/version.rb
Publishes stats to a waiting API when the tag "stats" runs.
`subspace provision production --tags=stats`
Edit vars like:
```
stats_url: https://dev.tenforward.services/api/client_stats
send_stats: true
stats_api_key: 81356f1bb434545ac410eac910316ff91a
```
=> Gather stats for Rails, Ruby, and Apt

CHANGELOG.md, ansible/roles/nginx-rails/defaults/main.yml, ansible/roles/nginx-rails/templates/nginx-project, ansible/roles/nginx-rails/templates/nginx-project-ssl, lib/subspace/version.rb
See issue #120 
We hardcoded the string "true" in there, so actual boolean True values are falsey when compared to that string.
The PR fixes that bug but leaves the former string option for backward-compatibility.
=> Fixes #120 - Checking for "true" string on ssl_force_redirect; adds config option for default_server

CHANGELOG.md, ansible/roles/letsencrypt/tasks/main.yml, ansible/roles/zenoamaro.postgresql/templates/postgresql.conf, lib/subspace/version.rb
* PostgreSQL database server works for version > 10. See details from Issue #125.
Just checking the version and only including the problematic directive if it's less than 10.
=> Fixed #125 remove invalid config parameter for versions < 10; and #127 for LetsEncrypt

CHANGELOG.md, README.md, ansible/roles/letsencrypt/tasks/main.yml, lib/subspace/version.rb
If this isn't present then it won't overwrite old certs and sometimes (unsure exactly when/why) letsencrypt will make directories like `/etc/letsencrypt/live/app.festbuddy.com-0002` which we don't want.
=> add cert_name flag for letsencrypt when cert names are not explicit

CHANGELOG.md, README.md, ansible/roles/newrelic-infra/defaults/main.yml, ansible/roles/newrelic-infra/handlers/main.yml, ansible/roles/newrelic-infra/tasks/main.yml, ansible/roles/newrelic-infra/templates/logs.yml.j2, ansible/roles/newrelic/tasks/main.yml, lib/subspace/cli.rb, lib/subspace/version.rb
* Add a friendly error message if ansible is not installed
* Add new role to support New Relic One's infrastructure agent
=> Ansible errors, newrelic infra

ansible/roles/letsencrypt/tasks/modern.yml
=> Add python3-certbot-nginx dependecy for modern letsencrypt setups

ansible/roles/common/tasks/main.yml
Make the OS Version string prettier for monthly reports and /software_versions page
=> Get the junk out of the os version string

CHANGELOG.md, ansible/roles/tailscale/tasks/main.yml, lib/subspace/version.rb
1.68.0 and higher are currently breaking ssh forwarding to github for deploy using capistrano
=> Pin tailscale to known good version

CHANGELOG.md, ansible/roles/tailscale/tasks/main.yml, lib/subspace/version.rb
This worked on wida dev, so long as `tailscale` role executes before `common` role
=> Fix tailscale unpinning/pinning; update changelog for new release
